// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CommPage struct {
	Comments   []*Comment `json:"comments"`
	TotalCount int        `json:"totalCount"`
}

type Comment struct {
	ID              string    `json:"id"`
	PostID          string    `json:"postId"`
	UserID          string    `json:"userId"`
	Author          *User     `json:"author"`
	Content         string    `json:"content"`
	ParentCommentID *string   `json:"parentCommentId,omitempty"`
	ReplyPage       *CommPage `json:"replyPage"`
}

type CreateCommentInput struct {
	UserID          string  `json:"userId"`
	PostID          string  `json:"postId"`
	Content         string  `json:"content"`
	ParentCommentID *string `json:"parentCommentId,omitempty"`
}

type CreatePostInput struct {
	UserID          string `json:"userId"`
	Title           string `json:"title"`
	Content         string `json:"content"`
	CommentsEnabled bool   `json:"commentsEnabled"`
}

type Mutation struct {
}

type Post struct {
	ID              string    `json:"id"`
	Title           string    `json:"title"`
	Content         string    `json:"content"`
	UserID          string    `json:"userId"`
	Author          *User     `json:"author"`
	CommentsEnabled bool      `json:"commentsEnabled"`
	CommPage        *CommPage `json:"commPage"`
}

type PostPage struct {
	Posts      []*Post `json:"posts"`
	TotalCount int     `json:"totalCount"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}
